/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as ConcursosRouteImport } from './routes/concursos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PlanejamentosRouteImport } from './routes/planejamentos'
import { Route as MapasMentaisIndexRouteImport } from './routes/mapas-mentais.index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizSubjectIdRouteImport } from './routes/quiz.$subjectId'
import { Route as MapasMentaisSubjectIdIndexRouteImport } from './routes/mapas-mentais.$subjectId.index'
import { Route as MapasMentaisSubjectIdTopicIdRouteImport } from './routes/mapas-mentais.$subjectId.$topicId'
import { Route as QuizSubjectIdIndexRouteImport } from './routes/quiz.$subjectId.index'
import { Route as QuizSubjectIdTopicIdRouteImport } from './routes/quiz.$subjectId.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosRoute = ConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentosRoute = PlanejamentosRouteImport.update({
  id: '/planejamentos',
  path: '/planejamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisIndexRoute = MapasMentaisIndexRouteImport.update({
  id: '/mapas-mentais/',
  path: '/mapas-mentais/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubjectIdRoute = QuizSubjectIdRouteImport.update({
  id: '/quiz/$subjectId',
  path: '/quiz/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisSubjectIdIndexRoute =
  MapasMentaisSubjectIdIndexRouteImport.update({
    id: '/mapas-mentais/$subjectId/',
    path: '/mapas-mentais/$subjectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MapasMentaisSubjectIdTopicIdRoute =
  MapasMentaisSubjectIdTopicIdRouteImport.update({
    id: '/mapas-mentais/$subjectId/$topicId',
    path: '/mapas-mentais/$subjectId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizSubjectIdIndexRoute = QuizSubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizSubjectIdRoute,
} as any)
const QuizSubjectIdTopicIdRoute = QuizSubjectIdTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => QuizSubjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/concursos': typeof ConcursosRoute
  '/historico': typeof HistoricoRoute
  '/painel': typeof PainelRoute
  '/planejamento': typeof PlanejamentoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/quiz/$subjectId': typeof QuizSubjectIdRouteWithChildren
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId/': typeof MapasMentaisSubjectIdIndexRoute
  '/quiz/$subjectId/': typeof QuizSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/concursos': typeof ConcursosRoute
  '/historico': typeof HistoricoRoute
  '/painel': typeof PainelRoute
  '/planejamento': typeof PlanejamentoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/mapas-mentais': typeof MapasMentaisIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId': typeof MapasMentaisSubjectIdIndexRoute
  '/quiz/$subjectId': typeof QuizSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/concursos': typeof ConcursosRoute
  '/historico': typeof HistoricoRoute
  '/painel': typeof PainelRoute
  '/planejamento': typeof PlanejamentoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/quiz/$subjectId': typeof QuizSubjectIdRouteWithChildren
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId/': typeof MapasMentaisSubjectIdIndexRoute
  '/quiz/$subjectId/': typeof QuizSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/concursos'
    | '/historico'
    | '/painel'
    | '/planejamento'
    | '/planejamentos'
    | '/quiz/$subjectId'
    | '/mapas-mentais/'
    | '/quiz/'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/quiz/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId/'
    | '/quiz/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/concursos'
    | '/historico'
    | '/painel'
    | '/planejamento'
    | '/planejamentos'
    | '/mapas-mentais'
    | '/quiz'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/quiz/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId'
    | '/quiz/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/concursos'
    | '/historico'
    | '/painel'
    | '/planejamento'
    | '/planejamentos'
    | '/quiz/$subjectId'
    | '/mapas-mentais/'
    | '/quiz/'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/quiz/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId/'
    | '/quiz/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  ConcursosRoute: typeof ConcursosRoute
  HistoricoRoute: typeof HistoricoRoute
  PainelRoute: typeof PainelRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  PlanejamentosRoute: typeof PlanejamentosRoute
  QuizSubjectIdRoute: typeof QuizSubjectIdRouteWithChildren
  MapasMentaisIndexRoute: typeof MapasMentaisIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  MapasMentaisSubjectIdTopicIdRoute: typeof MapasMentaisSubjectIdTopicIdRoute
  MapasMentaisSubjectIdIndexRoute: typeof MapasMentaisSubjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos': {
      id: '/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof ConcursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos': {
      id: '/planejamentos'
      path: '/planejamentos'
      fullPath: '/planejamentos'
      preLoaderRoute: typeof PlanejamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/': {
      id: '/mapas-mentais/'
      path: '/mapas-mentais'
      fullPath: '/mapas-mentais/'
      preLoaderRoute: typeof MapasMentaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subjectId': {
      id: '/quiz/$subjectId'
      path: '/quiz/$subjectId'
      fullPath: '/quiz/$subjectId'
      preLoaderRoute: typeof QuizSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/$subjectId/': {
      id: '/mapas-mentais/$subjectId/'
      path: '/mapas-mentais/$subjectId'
      fullPath: '/mapas-mentais/$subjectId/'
      preLoaderRoute: typeof MapasMentaisSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/$subjectId/$topicId': {
      id: '/mapas-mentais/$subjectId/$topicId'
      path: '/mapas-mentais/$subjectId/$topicId'
      fullPath: '/mapas-mentais/$subjectId/$topicId'
      preLoaderRoute: typeof MapasMentaisSubjectIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subjectId/': {
      id: '/quiz/$subjectId/'
      path: '/'
      fullPath: '/quiz/$subjectId/'
      preLoaderRoute: typeof QuizSubjectIdIndexRouteImport
      parentRoute: typeof QuizSubjectIdRoute
    }
    '/quiz/$subjectId/$topicId': {
      id: '/quiz/$subjectId/$topicId'
      path: '/$topicId'
      fullPath: '/quiz/$subjectId/$topicId'
      preLoaderRoute: typeof QuizSubjectIdTopicIdRouteImport
      parentRoute: typeof QuizSubjectIdRoute
    }
  }
}

interface QuizSubjectIdRouteChildren {
  QuizSubjectIdTopicIdRoute: typeof QuizSubjectIdTopicIdRoute
  QuizSubjectIdIndexRoute: typeof QuizSubjectIdIndexRoute
}

const QuizSubjectIdRouteChildren: QuizSubjectIdRouteChildren = {
  QuizSubjectIdTopicIdRoute: QuizSubjectIdTopicIdRoute,
  QuizSubjectIdIndexRoute: QuizSubjectIdIndexRoute,
}

const QuizSubjectIdRouteWithChildren = QuizSubjectIdRoute._addFileChildren(
  QuizSubjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  ConcursosRoute: ConcursosRoute,
  HistoricoRoute: HistoricoRoute,
  PainelRoute: PainelRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  PlanejamentosRoute: PlanejamentosRoute,
  QuizSubjectIdRoute: QuizSubjectIdRouteWithChildren,
  MapasMentaisIndexRoute: MapasMentaisIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  MapasMentaisSubjectIdTopicIdRoute: MapasMentaisSubjectIdTopicIdRoute,
  MapasMentaisSubjectIdIndexRoute: MapasMentaisSubjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
