/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PlanejamentosRouteImport } from './routes/planejamentos'
import { Route as MapasMentaisIndexRouteImport } from './routes/mapas-mentais.index'
import { Route as MapasMentaisSubjectIdIndexRouteImport } from './routes/mapas-mentais.$subjectId.index'
import { Route as MapasMentaisSubjectIdTopicIdRouteImport } from './routes/mapas-mentais.$subjectId.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentosRoute = PlanejamentosRouteImport.update({
  id: '/planejamentos',
  path: '/planejamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisIndexRoute = MapasMentaisIndexRouteImport.update({
  id: '/mapas-mentais/',
  path: '/mapas-mentais/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMentaisSubjectIdIndexRoute =
  MapasMentaisSubjectIdIndexRouteImport.update({
    id: '/mapas-mentais/$subjectId/',
    path: '/mapas-mentais/$subjectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MapasMentaisSubjectIdTopicIdRoute =
  MapasMentaisSubjectIdTopicIdRouteImport.update({
    id: '/mapas-mentais/$subjectId/$topicId',
    path: '/mapas-mentais/$subjectId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId/': typeof MapasMentaisSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/mapas-mentais': typeof MapasMentaisIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId': typeof MapasMentaisSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/planejamentos': typeof PlanejamentosRoute
  '/mapas-mentais/': typeof MapasMentaisIndexRoute
  '/mapas-mentais/$subjectId/$topicId': typeof MapasMentaisSubjectIdTopicIdRoute
  '/mapas-mentais/$subjectId/': typeof MapasMentaisSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historico'
    | '/planejamentos'
    | '/mapas-mentais/'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historico'
    | '/planejamentos'
    | '/mapas-mentais'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/historico'
    | '/planejamentos'
    | '/mapas-mentais/'
    | '/mapas-mentais/$subjectId/$topicId'
    | '/mapas-mentais/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  PlanejamentosRoute: typeof PlanejamentosRoute
  MapasMentaisIndexRoute: typeof MapasMentaisIndexRoute
  MapasMentaisSubjectIdTopicIdRoute: typeof MapasMentaisSubjectIdTopicIdRoute
  MapasMentaisSubjectIdIndexRoute: typeof MapasMentaisSubjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamentos': {
      id: '/planejamentos'
      path: '/planejamentos'
      fullPath: '/planejamentos'
      preLoaderRoute: typeof PlanejamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/': {
      id: '/mapas-mentais/'
      path: '/mapas-mentais'
      fullPath: '/mapas-mentais/'
      preLoaderRoute: typeof MapasMentaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/$subjectId/': {
      id: '/mapas-mentais/$subjectId/'
      path: '/mapas-mentais/$subjectId'
      fullPath: '/mapas-mentais/$subjectId/'
      preLoaderRoute: typeof MapasMentaisSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-mentais/$subjectId/$topicId': {
      id: '/mapas-mentais/$subjectId/$topicId'
      path: '/mapas-mentais/$subjectId/$topicId'
      fullPath: '/mapas-mentais/$subjectId/$topicId'
      preLoaderRoute: typeof MapasMentaisSubjectIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  PlanejamentosRoute: PlanejamentosRoute,
  MapasMentaisIndexRoute: MapasMentaisIndexRoute,
  MapasMentaisSubjectIdTopicIdRoute: MapasMentaisSubjectIdTopicIdRoute,
  MapasMentaisSubjectIdIndexRoute: MapasMentaisSubjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
